### ISSUE TITLE
Set Scopes

### ISSUE THREAD

**Issue by Flame2057** [nicholastay/passport-discord#13]
Why is there no way to set scopes? Only bot permissions? This whole package is useless.

**Comment by nicholastay** [comment]
check the example server

**Comment by neromaki** [comment]
Would've been pretty easy to just paste the example code instead of "check the example server":

```
var scopes = ['identify', 'email', 'guilds', 'guilds.join'];

passport.use(new Strategy({
    clientID: '',
    clientSecret: '',
    callbackURL: 'http://localhost:5000/callback',
    scope: scopes
}, function(accessToken, refreshToken, profile, done) {
    process.nextTick(function() {
        return done(null, profile);
    });
}));
```

Is the relevant code @owen-mills, presumably you need to pass an array of 1 if using a single scope such as `authorize` or `email`
