### ISSUE TITLE
User not defined

### ISSUE THREAD

**Issue by carloverhamme** [nicholastay/passport-discord#14]
var DiscordStrategy = require('passport-discord').Strategy;
 
passport.use(new DiscordStrategy({
    clientID: 'id',
    clientSecret: 'secret',
    callbackURL: 'callbackURL'
},
function(accessToken, refreshToken, profile, cb) {
    if (err)
        return done(err);
 
    User.findOrCreate({ discordId: profile.id }, function(err, user) {
        return cb(err, user);
    });
}));

---------------------------------------------------------------

"User" is undefined. Is there a way to define it?

**Comment by nicholastay** [comment]
This `User...` code is only an example. You must replace this part with your own desired callback. Check the example server for further guidance.
