### ISSUE TITLE
Allow setting value for `prompt`

### ISSUE THREAD

**Issue by theGordHoard** [nicholastay/passport-discord#20]
Discord's OAuth has a parameter `prompt` which allows you to control if a user is displayed the consent screen or not.
>` prompt` controls how the authorization flow handles existing authorizations. If a user has previously authorized your application with the requested scopes and prompt is set to `consent`, it will request them to reapprove their authorization. If set to `none`, it will skip the authorization screen and redirect them back to your redirect URI without requesting their authorization.

Allowing devs to set this value would be useful for websites that might have frequent traffic from consistent users.

**Comment by thewilloftheshadow** [comment]
Support. I really need this for my own application

**Comment by Zaydme** [comment]
This is really important!

**Comment by PLASMAchicken** [comment]
If it's so important, make a Pull Request, otherwise stop spamming the Comments thanks.

**Comment by nicholastay** [comment]
Resolved with #21
