### ISSUE TITLE
Invalid URI

### ISSUE THREAD

**Issue by Nuckerr** [nicholastay/passport-discord#31]
My auth.js file: 
`router.get('/discord/redirect', passpord.authenticate('discord'), (req, res) => {
   res.sendStatus(200);
});`
My discord.js file:
`passport.use(new DiscordStrategy({
        clientID: config.bot.client_id,
        clientSecret: config.bot.client_secret,
        callbackURL: config.bot.callback_url,
        scope: ['identify', 'guilds'],
        prompt: 'consent'
        },  function(accessToken, refreshToken, profile, done) { }));`

And I get an invalid uri error

(I would post this in a support discord server but I cant seem to find one)

**Comment by officialpiyush** [comment]
Can you check if the callback URL you passed as an option is one of the URL specified in the `Redirects` in the oauth2 section of your application page?

Image reference:
![image](https://user-images.githubusercontent.com/18086566/98468004-8a432c80-21fe-11eb-91ec-80e72eb05bd2.png)

**Comment by Nuckerr** [comment]
http://i.nucker.me/ZLjdD.png

**Comment by officialpiyush** [comment]
I see, what's the value of `config.bot.callback_url`?

**Comment by nodgear** [comment]
Remember to use `/` in the end of link on developer portal...

**Comment by Nuckerr** [comment]
ooh that might have been the problem, I will see when I come back to this project
