### ISSUE TITLE
Working one day, the next not

### ISSUE THREAD

**Issue by KingCh1ll** [nicholastay/passport-discord#46]
Yesterday, it was working fine for me. Today, however, when I tried to login, I got failed to access token.
https://cdn.ch1ll.tk/chrome_qSbsnksnm4.png

**Comment by FAXES** [comment]
Your image isn't found, consider uploading it to GitHub so it can be viewed anytime <3

**Comment by KingCh1ll** [comment]
> Your image isn't found, consider uploading it to GitHub so it can be viewed anytime ❤️

dude it's been over a year 😭
Anyways, it was probably due to rate limits as I was using replit at the time. Now I have my own VPS and have my own session manager.

**Comment by FAXES** [comment]
> > Your image isn't found, consider uploading it to GitHub so it can be viewed anytime ❤️
> 
> dude it's been over a year 😭 Anyways, it was probably due to rate limits as I was using replit at the time. Now I have my own VPS and have my own session manager.

Cool stuff ❤️, didn't see the time difference oops 😂
