### ISSUE TITLE
TypeError: Strategy is not a constructor

### ISSUE THREAD

**Issue by BrydenIsNotSmart** [nicholastay/passport-discord#51]
TypeError: Strategy is not a constructor

**Comment by CorwinDev** [comment]
Can you show your code?

**Comment by BrydenIsNotSmart** [comment]
![Screenshot 2022-08-03 193027](https://user-images.githubusercontent.com/67612593/182737889-28496003-20f7-4d15-9a61-78ced20e2fab.png)

**Comment by BrydenIsNotSmart** [comment]
I fixed it, never mind. Thanks for trying to help me though.

**Comment by gamerdave08** [comment]
i have a error like this too can you help me ? 
![image](https://user-images.githubusercontent.com/103964866/222897123-ede85748-6710-4381-895b-ac0759c0e340.png)
